import type { Metadata } from "next";
import { Footer, Header } from "../app/core/components";
import "./core/styles/globals.scss";
import { ReduxProvider } from "./core/store/Providers";

export const metadata: Metadata = {
	title: "eMassage - Главная",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<ReduxProvider>
					<Header />
					{children}
					<Footer />
				</ReduxProvider>
			</body>
		</html>
	);
}
