import type { Metadata } from "next";
import { Footer, Header } from "../app/core/components";
import "./core/styles/globals.scss";

export const metadata: Metadata = {
	title: "eMassage - Главная",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
